### PR TITLE
Add support for Roomba i7/i7+ discovery

### PR DESCRIPTION
**Pull request by ady624**
Adds support for Roomba i7 discovery - this allows users to find the BLID for the robot.

### CODE REVIEW

**Comment by koalazak** [comment]
Hi, @ady624 
thank you! Can you increase the patch version in package.json?
did you test all the functions? if so, please also edit and add the i7 model in Readme section "features": `Compatible robots: all 800 and 900 series with HOME app.`

thank you again!

**Comment by Madj42** [comment]
I can confirm that this does indeed allow for discovery of i7+ devices.  I wasn't able to discover the i7+ until I had implemented this fix manually.  I haven't tested all functionality of th device but I can confirm using rest980, I'm able to start and stop a cleaning cycle, get the status of the device, etc.

**Comment by koalazak** [comment]
thanks @Madj42! I just pushed the fix in dorita980@3.0.13 with readme and package.json updates too.
thanks guys,

**Comment by ady624** [comment]
Sorry guys, late to the punch. Thanks for taking care of it.

**Comment by ady624** [comment]
Actually, I see the change is not yet in master - do you still need me to do anything? I'd be happy to help.

Thanks,
Adrian

**Comment by koalazak** [comment]
I pushed the change but only in the getRobotPublicInfo() method (just like your commit). But now I pushed into discovery() method too.
thanks

**Pull request closed without merging**
