### PR TITLE
Added find command

### PR DESCRIPTION
**Pull request by matthijs2704**
Possibly needs tests though

### CODE REVIEW

**Comment by koalazak** [comment]
hi @matthijs2704! thanks!
Can you write the test, add documentation in readme.md and increase the package version (minor) in package.json before merge?

thnaks!

**Comment by koalazak** [comment]
@matthijs2704 are you on that?

**Comment by matthijs2704** [comment]
Yeah, I'll once I find a little time to do so 😃 Just have been extremely busy lately and haven't gotten around to do it yet...

**Comment by koalazak** [comment]
i will add this in future commits

**Pull request closed without merging**
